version: '3'
services:
  attendancemanagement-backend-api:
    image: attendance-management-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
      
  attendancemanagement-frontend-vue:
    image: attendancemanagement-frontend-vue
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VUE_APP_API_URL: http://localhost:8080
    ports:
      - "8081:80"
    depends_on:
      - phone-book-api
