version: '3'
services:
  attendancemanagement-backend-api:
    image: 565346696680.dkr.ecr.ap-northeast-1.amazonaws.com/attendancemanagement:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:80"

  attendancemanagement-frontend-vue:
    image: 565346696680.dkr.ecr.ap-northeast-1.amazonaws.com/attendancemanagement:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VUE_APP_API_URL: http://localhost:8080
    ports:
      - "8081:80"
    depends_on:
      - attendancemanagement-backend-api
