name: Build .net core S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./src/backend/WebAPI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Deploy  
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp --recursive --region ap-northeast-1 /home/runner/work/AttendanceManagement/AttendanceManagement/src/backend/WebAPI/bin/Release/net6.0/ s3://attendancemanagemenapi
